sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t khossain/react-test -f ./client/Dockerfile.dev ./client
  # build client dev image for testing
  # build server image for testing
  # build worker image for testing

script:
  - docker run khossain/react-test npm run test -- --coverage
  # if we don't flag coverage then react test will wait infinitely
  # add server side test command. e.g: - docker run khaled/server npm test 
  # add client side test command

# build production image to deploy
  # log in to docker hub to deploy these images
  # set dockerID and pass to travisCI envrionment variable
  # push production images to docker hub 
after_success:
  - docker build -t khossain/multi-client ./client
  - docker build -t khossain/multi-nginx ./nginx
  - docker build -t khossain/multi-server ./server
  - docker build -t khossain/multi-worker ./worker
  # password must be without speacial character, if we use special character we have to use escape
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push khossain/multi-client
  - docker push khossain/multi-nginx
  - docker push khossain/multi-server
  - docker push khossain/multi-worker

