#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push khossain/multi-client
docker push khossain/multi-nginx
docker push khossain/multi-server
docker push khossain/multi-worker